version: '3'

services:
  datafarm:
    build: ./
    container_name: datafarm_trading
    command: ["python3", "main.py"]
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env